linters:
  enable-all: true
  disable:
    - bodyclose
    - cyclop
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomnd
    - lll
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - revive
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint

linters-settings:
  #
  # The G108 rule throws a false positive. We're not actually vulnerable. If
  # you're not careful the profiling endpoint is automatically exposed on
  # /debug/pprof if you import net/http/pprof. See this link:
  #
  #   https://mmcloughlin.com/posts/your-pprof-is-showing
  #
  gosec:
    excludes:
      - G108

  tagliatelle:
    case:
      rules:
        json: snake

  gofumpt:
    extra-rules: true
